version: '3.8'

services:

  SCM:
    image: scmxperlite:latest
    ports:
      - "8081:8081"

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    depends_on:
      - SCM
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  servers: 
    image: scmxperlite/server:latest
    ports:
      - "12345:12345"
    depends_on:
      - kafka

  producer:
    image: scmxperlite/producer:latest
    depends_on:
      - servers

  consumer:
    image: scmxperlite/consumer:latest
    depends_on:
      - producer
